### ISSUE TITLE
The reverse() function should ignore sections inside paratheses

### ISSUE THREAD

**Issue by snirp** [tricoder42/named-urls#16]
React router uses parentheses to include regular expressions to validate arguments. Here is an example.
 
```
item:  '/item/:name(foo|bar)'
```

Using `reverse(item, {name: 'foo'})` results in:

```
/item/foo(foo|bar)
```

**Comment by tricoder42** [comment]
Thank you for observation. Please provide a PR if you want to fix it.

**Comment by snirp** [comment]
Yes I will, may take me some time to do that correctly though. Not just simply a question of replacing everything in parentheses in the pattern: literal parentheses denoted by `/(` ... `/)` should be preserved

**Comment by sarahdayan** [comment]
I need this too 🙂 I'd love to provide a PR if nobody has time, otherwise I'll havz to fork and I'd rather not.

As far as I can tell, it's not only what's in between parentheses, but *"any valid URL path or array of paths that path-to-regexp@^1.7.0 understands."* ([source](https://reacttraining.com/react-router/web/api/Route/path-string-string)). So it may make sense to use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) directly in the library to compile the reversed route instead of using custom regexps.

Example on RunKit: https://runkit.com/embed/sg69splpe9c0

**Comment by tricoder42** [comment]
@sarahdayan PRs are always welcome :) Using `path-to-regexp` sounds good if it solves the problem. Is it going to work with optional parameters?

**Comment by sarahdayan** [comment]
@tricoder42 That's exactly what I'm looking into :) Unit tests will tell us. Will PR as soon as I can.

**Comment by sarahdayan** [comment]
@tricoder42 I'm seeing a first problem with the following tests:

```
expect(reverse('pattern/page:param?', {})).toEqual('pattern')
expect(reverse('pattern/page:param?/', {})).toEqual('pattern/')
```

They assume that `page:param` is the optional parameter (thus should be trimmed). For `path-to-regexp`, `param` is the optional parameter (as `:` is the delimiter for parameters), so `?` applies to `param`. Therefore, it would trim to `pattern/page`, not `pattern`.

If we wanted to literally match on "page:param", then a `pattern/(page:param)?/` would be necessary. It also feels clearer: the parentheses remove ambiguity.

Since the library is intended to sit on top of React Router, and RR itself relies on `path-to-regexp`, I would definitely recommend going for how `path-to-regexp` understands pattern, and change the expectation on these tests. **This means breaking backwards compatibility.**

I definitely understand that going for a new major version may not be an option. We could create a new function, but it would add complexity (now you have two ways of writing patterns). WDYT?

**Comment by tricoder42** [comment]
@sarahdayan I don't mind releasing major version. I like the fact that the library will use the same patters as React Router. So, let's do it 👍 

Thank you for working on this!
